# Generated by Django 2.1 on 2018-09-19 09:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(default='', upload_to='mainApp/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Icon')),
            ],
        ),
    ]
